apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: tkachikaa/lab3_pdris:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "example"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 8080
  type: NodePort
